### PR TITLE
Basic LMDB support. 

### PR DESCRIPTION
**Pull request by ghenry**
Hi Brett,

I was supposed to be in London all today, but it was cancelled. I decided to play with this and LMDB and add support for it here with tests. I'm not sure about the copyright bit, so please change.

I hope you don't mind? I still need to complete *fetch_all and add mdb_cursor_* support.

Gavin.

### CODE REVIEW

**Comment by brettsheffield** [comment]
Merged with a few formatting changes: https://github.com/brettsheffield/libgladdb/commit/25934ff22f07dd094eb5ed3ab6fc51675f1b6d29

**Comment by brettsheffield** [comment]
I've reformatted the code to use 8 character tabs rather than spaces, as per the rest of the project and added the CONTRIBUTING file to clarify that this project uses the Linux kernel coding style.

**Comment by ghenry** [comment]
Apologies. I use https://github.com/tpope/vim-sleuth and it detected things
wrongly.

**Comment by brettsheffield** [comment]
No worries.

**Pull request closed without merging**
